# Spring Boot Configuration in YAML Format
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DeliveryDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: delivery
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  mvc:
    format:
      date-time: dd-MM-yyyy'T'HH:mm:ss
      date: dd-MM-yyyy'T'HH:mm:ss
      time: HH:mm:ss
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 15MB
      max-request-size: 15MB
